Fixed Doc URLs, added header, prototype for ratelimit backing off
funnyboy-roks/modrinth-auto-desc pull request #1
Opened 2024-10-01 18:10 UTC by akr4s1a

Hi there, I saw this project in Modtoberfest and saw I could add a few small things.

- I've changed the docs URLs to remove api-spec/ so they resolve 
- I added a header using the supplied slug. 
- I wanted to contribute a mechanism to take the rate limit supplied by the response in https://docs.modrinth.com/#section/Ratelimits 

but without a local testing environment I didn't feel comfortable leaving the rate limit mechanism in. It will need a way to send the request again, sendRequest() could be encapsulated and moved

2024-10-01 22:04 UTC, funnyboy-roks commented
Thank you for your PR!

- Thank you for updating the docs urls
- For the user agent, we should be more specific.  Something like: `<project-id> via funnyboy-roks/modrinth-auto-desc` would work for me.
- For the rate limit, I think this is a good idea to implement, though I don't have a good setup for testing this at the moment.  Would you be willing to put that in a second PR, so that we can merge the other two things in this PR and look at that in the future?

2024-10-01 22:26 UTC, akr4s1a commented
Sure I can split off the rate limiting and open a draft PR for that.

For getting project-id for a better user-agent, what do you think the best way to go about it is? I think adding optional entries in front matter could be good for getting contact info and to specify the project.

2024-10-01 22:32 UTC, funnyboy-roks commented
We can add those as optional arguments for the action.  See the [action.yml](https://github.com/funnyboy-roks/modrinth-auto-desc/blob/main/action.yml) file, so add a `project-name` field and if set, use `<project-name> (<slug>) via funnyboy-roks/modrinth-auto-desc` and if not set then just `<slug> via funnyboy-roks/modrinth-auto-desc`.

I do want to keep the slug in the user agent, in case the user sets a bad project name.

2024-10-01 22:54 UTC, akr4s1a commented
Something like this?

2024-10-02 00:32 UTC, funnyboy-roks requested changes
Looks good, just minor issues

2024-10-02 00:32 UTC, funnyboy-roks commented on action.yml
> +    default: 'REPLACEME'
This is good, would prefer the default to be something more like `__unset`

2024-10-02 00:32 UTC, funnyboy-roks commented on index.js
> +        user_agent = user_agent == "REPLACEME" ? slug : `${user_agent} (${slug})`
Very nitpicky, but can you use single quotes (`'`) instead of the double quotes (`"`)

2024-10-02 00:42 UTC, funnyboy-roks approved these changes
Looks good!

2024-10-02 00:43 UTC, merged